"""Main entry point"""

import argparse
import json
import subprocess
from pathlib import Path
from typing import Callable

from ._version import __version__
from .go import add_go_cmd
from .java import add_java_cmd


def get_schema(filename: str) -> dict:
    """Load Chatmail JSON-RPC schema from file path"""
    if filename:
        with Path(filename).open(encoding="utf-8") as schema_file:
            return json.load(schema_file)
    return {}


def get_parser() -> argparse.ArgumentParser:
    """Create CLI argument parser"""
    base = argparse.ArgumentParser(add_help=False)
    base.add_argument(
        "-o",
        "--output",
        help="output folder (default: generated)",
        type=Path,
        metavar="FOLDER",
        dest="folder",
        default=argparse.SUPPRESS,
    )
    base.add_argument(
        "--schema",
        help=(
            "OpenRPC schema file as generated by deltachat-rpc-server --openrpc."
            " If not set, deltachat-rpc-server will be called directly"
        ),
        type=get_schema,
        metavar="PATH",
        dest="openrpc_spec",
        default=argparse.SUPPRESS,
    )

    parser = argparse.ArgumentParser(
        description="Chatmail JSON-RPC client generator", parents=[base]
    )
    parser.add_argument("-v", "--version", action="version", version=__version__)
    subparsers = parser.add_subparsers(title="subcommands")

    for add_generator in [add_java_cmd, add_go_cmd]:
        add_generator(subparsers, base)

    return parser


def main(args=None) -> None:
    """Application entry point"""
    parser = get_parser()
    args = parser.parse_args(args=args)
    if not hasattr(args, "func"):
        parser.parse_args(["-h"])
    if not hasattr(args, "folder"):
        args.folder = Path("generated")

    if not hasattr(args, "openrpc_spec") or not args.openrpc_spec:
        cmd = "deltachat-rpc-server"
        print("WARNING: no schema file provided, trying to generate it using", cmd)
        args.openrpc_spec = json.loads(
            subprocess.run([cmd, "--openrpc"], capture_output=True, check=True).stdout
        )

    args.func(args)
