strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - docs
  - build

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pycodestyle:
  disable:
    - E501

pylint:
  disable:
     - line-too-long
     - too-many-arguments
     - too-many-branches
     - too-many-locals
     - too-many-boolean-expressions
     - too-many-positional-arguments

mccabe:
  run: false

mypy:
  run: true
