"""Utilities for Python code generation."""

from typing import Any


def get_banner() -> str:
    """Get common banner comment to be added at the start of generated files"""
    return "# Autogenerated file, do not edit manually"


def create_comment(text: str, indentation: str = "") -> str:
    """Generate a Python docstring comment"""
    lines = text.strip().splitlines()
    if len(lines) == 1:
        return f'{indentation}"""{lines[0].strip()}"""\n'
    result = f'{indentation}"""\n'
    for line in lines:
        stripped = line.strip()
        if stripped:
            result += f"{indentation}{stripped}\n"
        else:
            result += "\n"
    result += f'{indentation}"""\n'
    return result


def create_inline_comment(text: str, indentation: str = "") -> str:
    """Generate Python # comment lines (for use inside enums and other non-docstring contexts)"""
    result = ""
    for line in text.strip().splitlines():
        stripped = line.strip()
        if stripped:
            result += f"{indentation}# {stripped}\n"
        else:
            result += f"{indentation}#\n"
    return result


def decode_type(
    property_desc: dict[str, Any],
) -> tuple[str, bool]:  # pylint: disable=too-many-branches,too-many-statements
    """Decode a JSON schema type descriptor to a Python type string.

    Returns (python_type, is_optional) where is_optional means the field can be null/absent.
    """
    if "anyOf" in property_desc:
        assert len(property_desc["anyOf"]) == 2
        assert property_desc["anyOf"][1] == {"type": "null"}
        inner = property_desc["anyOf"][0]
        inner_type = decode_type(inner)[0]
        return f"Optional[{inner_type}]", True

    if "$ref" in property_desc:
        assert property_desc["$ref"].startswith("#/components/schemas/")
        typ = property_desc["$ref"].removeprefix("#/components/schemas/")
        return typ, False

    prop_type = property_desc.get("type")

    if prop_type == "null":
        return "None", False  # only for function return type

    # Handle nullable types represented as ["type", "null"]
    if isinstance(prop_type, list):
        assert len(prop_type) == 2
        assert "null" in prop_type
        inner_type_name = next(t for t in prop_type if t != "null")
        inner_desc = dict(property_desc)
        inner_desc["type"] = inner_type_name
        inner_py_type = decode_type(inner_desc)[0]
        return f"Optional[{inner_py_type}]", True

    if prop_type == "boolean":
        return "bool", False
    if prop_type == "integer":
        return "int", False
    if prop_type == "number":
        return "float", False
    if prop_type == "string":
        return "str", False
    if prop_type == "array":
        items = property_desc["items"]
        if isinstance(items, list):
            count = len(items)
            if count == 2:
                typ1 = decode_type(items[0])[0]
                typ2 = decode_type(items[1])[0]
                return f"tuple[{typ1}, {typ2}]", False
            raise ValueError(f"Tuple not implemented for {count} elements: {property_desc}")
        items_type = decode_type(items)[0]
        return f"list[{items_type}]", False
    if "additionalProperties" in property_desc:
        value_type = decode_type(property_desc["additionalProperties"])[0]
        return f"dict[str, {value_type}]", False

    raise ValueError(f"Not supported: {property_desc!r}")


def decode_optional_type(property_desc: dict[str, Any]) -> str:
    """Decode a type, ensuring the result is always Optional for non-required fields."""
    type_str, is_optional = decode_type(property_desc)
    if is_optional:
        return type_str
    return f"Optional[{type_str}]"
