"""Utilities for Python code generation."""

from typing import Any


def get_banner() -> str:
    """Get common banner comment to be added at the start of generated files"""
    return "# Autogenerated file, do not edit manually"


def create_comment(text: str, indentation: str = "", docstr: bool = False) -> str:
    """Generate a Python comment or docstring"""
    if docstr:
        if "\n" not in text:
            return f'{indentation}"""{text.strip()}"""\n'
        comment = f'{indentation}"""\n'
        for line in text.split("\n"):
            comment += f"{indentation}{line.strip()}\n"
        return comment + f'{indentation}"""\n'

    if "\n" not in text:
        return f"{indentation}# {text.strip()}\n"
    comment = ""
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped:
            comment += f"{indentation}# {stripped}\n"
        else:
            comment += f"{indentation}#\n"
    return comment


def decode_type(  # pylint: disable=too-many-branches,too-many-statements
    property_desc: dict[str, Any],
) -> str:
    """Decode a JSON schema type descriptor to a Python type string."""
    schemas_url = "#/components/schemas/"

    if "anyOf" in property_desc:
        assert len(property_desc["anyOf"]) == 2
        assert property_desc["anyOf"][1] == {"type": "null"}
        inner = property_desc["anyOf"][0]
        if "$ref" in inner:
            typ = inner["$ref"].removeprefix(schemas_url)
        else:
            typ = decode_type(inner)
        return f"Optional[{typ}]"

    if "$ref" in property_desc:
        assert property_desc["$ref"].startswith(schemas_url)
        return property_desc["$ref"].removeprefix(schemas_url)

    prop_type = property_desc.get("type")

    if prop_type == "null":
        return "None"  # only for function return type

    # Handle nullable types represented as ["type", "null"]
    if isinstance(prop_type, list):
        assert len(prop_type) == 2
        assert "null" in prop_type
        inner_type_name = next(t for t in prop_type if t != "null")
        inner_desc = dict(property_desc)
        inner_desc["type"] = inner_type_name
        return f"Optional[{decode_type(inner_desc)}]"

    if prop_type == "boolean":
        return "bool"
    if prop_type == "integer":
        return "int"
    if prop_type == "number":
        return "float"
    if prop_type == "string":
        return "str"
    if prop_type == "array":
        items = property_desc["items"]
        if isinstance(items, list):
            count = len(items)
            if count == 2:
                return f"tuple[{decode_type(items[0])}, {decode_type(items[1])}]"
            raise ValueError(f"Tuple not implemented for {count} elements: {property_desc}")
        return f"list[{decode_type(items)}]"
    if "additionalProperties" in property_desc:
        return f"dict[str, {decode_type(property_desc['additionalProperties'])}]"

    raise ValueError(f"Not supported: {property_desc!r}")
